stages:
  - setup
  - test
  - lint

variables:
  # Define the Python version you want to use
  PYTHON_VERSION: "3.8"

before_script:
  # Update and install Python
  - apt-get update -y
  - apt-get install -y python${PYTHON_VERSION} python3-pip

setup:
  stage: setup
  script:
    - python3 --version
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - pip3 install pytest
    - pytest tests/

lint:
  stage: lint
  script:
    - pip3 install flake8
    - flake8 .

# Caching pip packages will speed up the job
cache:
  paths:
    - .cache/pip

# This is an example of how to define the job using Docker images
image: python:${PYTHON_VERSION}
